version: '3.8'

services:
  # Pool de Desafios e Broker de Mensageria (Mantemos local)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  # API Principal
  api:
    build: .
    # Agora ele cria as tabelas no Supabase antes de rodar o servidor!
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # Conectando direto no Supabase:
      - DATABASE_URL=postgresql://postgres:iIUF6N5we5expC52@db.xmxddvlonfhaqprdubar.supabase.co:5432/postgres
    depends_on:
      - redis

  # Worker Assíncrono (Processa a IA em background)
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # Conectando direto no Supabase:
      - DATABASE_URL=postgresql://postgres:iIUF6N5we5expC52@db.xmxddvlonfhaqprdubar.supabase.co:5432/postgres
      # Lembre-se de configurar a chave no seu arquivo .env
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    depends_on:
      - redis

# Como o banco foi pra nuvem, não precisamos mais do bloco 'volumes' aqui embaixo!