# Generated by Django 5.2.12 on 2026-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioEstatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='ID ou título do vídeo', max_length=100)),
                ('pergunta', models.TextField()),
                ('resposta_correta', models.CharField(max_length=255)),
                ('alternativas', models.JSONField(help_text='Lista de alternativas em JSON')),
            ],
        ),
    ]
